apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}{{ .Values.environment.suffix }}-secrets
  labels:
    app: {{ .Chart.Name }}{{ .Values.environment.suffix }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.application.jwt.secret | quote }}
  DB_PASSWORD: {{ .Values.application.database.password | quote }}
  EMAIL_PASSWORD: {{ .Values.application.email.password | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.application.sso.google.clientSecret | quote }}
