apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}{{ .Values.environment.suffix }}
  labels:
    app: {{ .Chart.Name }}{{ .Values.environment.suffix }}
spec:
  serviceName: {{ .Chart.Name }}{{ .Values.environment.suffix }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}{{ .Values.environment.suffix }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}{{ .Values.environment.suffix }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
          name: http
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: config
          mountPath: /app/config
          readOnly: true
        env:
        - name: SPRING_CONFIG_LOCATION
          value: "file:/app/config/application.properties"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}{{ .Values.environment.suffix }}-secrets
              key: JWT_SECRET
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}{{ .Values.environment.suffix }}-secrets
              key: DB_PASSWORD
        - name: EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}{{ .Values.environment.suffix }}-secrets
              key: EMAIL_PASSWORD
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}{{ .Values.environment.suffix }}-secrets
              key: GOOGLE_CLIENT_SECRET
      volumes:
      - name: config
        configMap:
          name: {{ .Chart.Name }}{{ .Values.environment.suffix }}-config
  {{- if .Values.volumeClaimTemplates.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.volumeClaimTemplates.storageClassName }}
      resources:
        requests:
          storage: {{ .Values.volumeClaimTemplates.storage }}
  {{- end }}
